package com.itc.dbservice.models;
// Generated 5 Jan, 2019 8:40:26 PM by Hibernate Tools 5.0.6.Final

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CointCtolocal generated by hbm2java
 */
@Entity
@Table(name = "coint_ctolocal", schema = "alert_schema")
public class CointCtolocal implements Serializable {

	private CointCtolocalId id;
	private String e1243CodSort;
	private String e1243Idctoloc;
	private String e1243Ctolocpr;
	private String e1243Fecalta;
	private String e1243Usualta;
	private Serializable uuid;

	public CointCtolocal() {
	}

	public CointCtolocal(CointCtolocalId id, Serializable uuid) {
		this.id = id;
		this.uuid = uuid;
	}

	public CointCtolocal(CointCtolocalId id, String e1243CodSort, String e1243Idctoloc, String e1243Ctolocpr,
			String e1243Fecalta, String e1243Usualta, Serializable uuid) {
		this.id = id;
		this.e1243CodSort = e1243CodSort;
		this.e1243Idctoloc = e1243Idctoloc;
		this.e1243Ctolocpr = e1243Ctolocpr;
		this.e1243Fecalta = e1243Fecalta;
		this.e1243Usualta = e1243Usualta;
		this.uuid = uuid;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "e1243Idempr", column = @Column(name = "e1243_idempr", nullable = false, length = 4)),
			@AttributeOverride(name = "e1243Idcent", column = @Column(name = "e1243_idcent", nullable = false, length = 4)),
			@AttributeOverride(name = "e1243Idprod", column = @Column(name = "e1243_idprod", nullable = false, length = 3)),
			@AttributeOverride(name = "e1243Idcontr", column = @Column(name = "e1243_idcontr", nullable = false, length = 7)) })
	public CointCtolocalId getId() {
		return this.id;
	}

	public void setId(CointCtolocalId id) {
		this.id = id;
	}

	@Column(name = "e1243_cod_sort", length = 6)
	public String getE1243CodSort() {
		return this.e1243CodSort;
	}

	public void setE1243CodSort(String e1243CodSort) {
		this.e1243CodSort = e1243CodSort;
	}

	@Column(name = "e1243_idctoloc", length = 16)
	public String getE1243Idctoloc() {
		return this.e1243Idctoloc;
	}

	public void setE1243Idctoloc(String e1243Idctoloc) {
		this.e1243Idctoloc = e1243Idctoloc;
	}

	@Column(name = "e1243_ctolocpr", length = 40)
	public String getE1243Ctolocpr() {
		return this.e1243Ctolocpr;
	}

	public void setE1243Ctolocpr(String e1243Ctolocpr) {
		this.e1243Ctolocpr = e1243Ctolocpr;
	}

	@Column(name = "e1243_fecalta", length = 40)
	public String getE1243Fecalta() {
		return this.e1243Fecalta;
	}

	public void setE1243Fecalta(String e1243Fecalta) {
		this.e1243Fecalta = e1243Fecalta;
	}

	@Column(name = "e1243_usualta", length = 8)
	public String getE1243Usualta() {
		return this.e1243Usualta;
	}

	public void setE1243Usualta(String e1243Usualta) {
		this.e1243Usualta = e1243Usualta;
	}

	@Column(name = "uuid_", nullable = false)
	public Serializable getUuid() {
		return this.uuid;
	}

	public void setUuid(Serializable uuid) {
		this.uuid = uuid;
	}

}
