package com.itc.dbservice.models;
// Generated 5 Jan, 2019 8:40:26 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DirElectronicaId generated by hbm2java
 */
@Embeddable
public class DirElectronicaId implements java.io.Serializable {

	private char direTipopers;
	private int direCodpers;
	private String direIddispo;
	private short direJnrosec;

	public DirElectronicaId() {
	}

	public DirElectronicaId(char direTipopers, int direCodpers, String direIddispo, short direJnrosec) {
		this.direTipopers = direTipopers;
		this.direCodpers = direCodpers;
		this.direIddispo = direIddispo;
		this.direJnrosec = direJnrosec;
	}

	@Column(name = "dire_tipopers", nullable = false, length = 1)
	public char getDireTipopers() {
		return this.direTipopers;
	}

	public void setDireTipopers(char direTipopers) {
		this.direTipopers = direTipopers;
	}

	@Column(name = "dire_codpers", nullable = false, precision = 9, scale = 0)
	public int getDireCodpers() {
		return this.direCodpers;
	}

	public void setDireCodpers(int direCodpers) {
		this.direCodpers = direCodpers;
	}

	@Column(name = "dire_iddispo", nullable = false, length = 3)
	public String getDireIddispo() {
		return this.direIddispo;
	}

	public void setDireIddispo(String direIddispo) {
		this.direIddispo = direIddispo;
	}

	@Column(name = "dire_jnrosec", nullable = false, precision = 3, scale = 0)
	public short getDireJnrosec() {
		return this.direJnrosec;
	}

	public void setDireJnrosec(short direJnrosec) {
		this.direJnrosec = direJnrosec;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DirElectronicaId))
			return false;
		DirElectronicaId castOther = (DirElectronicaId) other;

		return (this.getDireTipopers() == castOther.getDireTipopers())
				&& (this.getDireCodpers() == castOther.getDireCodpers())
				&& ((this.getDireIddispo() == castOther.getDireIddispo())
						|| (this.getDireIddispo() != null && castOther.getDireIddispo() != null
								&& this.getDireIddispo().equals(castOther.getDireIddispo())))
				&& (this.getDireJnrosec() == castOther.getDireJnrosec());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDireTipopers();
		result = 37 * result + this.getDireCodpers();
		result = 37 * result + (getDireIddispo() == null ? 0 : this.getDireIddispo().hashCode());
		result = 37 * result + this.getDireJnrosec();
		return result;
	}

}
