package com.itc.dbservice.models;
// Generated 5 Jan, 2019 8:40:26 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersFisicaUk generated by hbm2java
 */
@Entity
@Table(name = "pers_fisica_uk", schema = "alert_schema")
public class PersFisicaUk implements java.io.Serializable {

	private PersFisicaUkId id;
	private String e0476CodAbr;
	private String e0476TipTra;
	private String e0476FirstNm;
	private String e0476MiddlNm;
	private String e0476LastNm;
	private String e0476TipSufx;
	private String e0476KnownAs;
	private String e0476MaidnNm;
	private String e0476Infsrctp;
	private String e0476Paisnac;
	private Date e0476FecCt;
	private Character e0476SexoPer;
	private Character e0476TipoEst;
	private Date e0476Fechnaci;
	private String e0476IndNiva;
	private Character e0476Indemple;
	private String e0476Paisresi;
	private String e0476Csecbes;
	private String e0476Cnae93;
	private String e0476Nivestud;
	private Character e0476Codidio;
	private String e0476Idemprpp;
	private String e0476Incli;
	private String e0476Cpais2na;
	private Date e0476FecDece;
	private Character e0476Swtrabj;
	private String e0476Cno;
	private Date e0476Fecaltsi;
	private String e0476Usultact;
	private String e0476Emultact;
	private String e0476Ceultact;
	private Date e0476Feultact;
	private Date e0476HorUlta;
	private String e0476Indicado;
	private String e0476Codpais;
	private String e0476Paisresf;

	public PersFisicaUk() {
	}

	public PersFisicaUk(PersFisicaUkId id, String e0476LastNm) {
		this.id = id;
		this.e0476LastNm = e0476LastNm;
	}

	public PersFisicaUk(PersFisicaUkId id, String e0476CodAbr, String e0476TipTra, String e0476FirstNm,
			String e0476MiddlNm, String e0476LastNm, String e0476TipSufx, String e0476KnownAs, String e0476MaidnNm,
			String e0476Infsrctp, String e0476Paisnac, Date e0476FecCt, Character e0476SexoPer, Character e0476TipoEst,
			Date e0476Fechnaci, String e0476IndNiva, Character e0476Indemple, String e0476Paisresi, String e0476Csecbes,
			String e0476Cnae93, String e0476Nivestud, Character e0476Codidio, String e0476Idemprpp, String e0476Incli,
			String e0476Cpais2na, Date e0476FecDece, Character e0476Swtrabj, String e0476Cno, Date e0476Fecaltsi,
			String e0476Usultact, String e0476Emultact, String e0476Ceultact, Date e0476Feultact, Date e0476HorUlta,
			String e0476Indicado, String e0476Codpais, String e0476Paisresf) {
		this.id = id;
		this.e0476CodAbr = e0476CodAbr;
		this.e0476TipTra = e0476TipTra;
		this.e0476FirstNm = e0476FirstNm;
		this.e0476MiddlNm = e0476MiddlNm;
		this.e0476LastNm = e0476LastNm;
		this.e0476TipSufx = e0476TipSufx;
		this.e0476KnownAs = e0476KnownAs;
		this.e0476MaidnNm = e0476MaidnNm;
		this.e0476Infsrctp = e0476Infsrctp;
		this.e0476Paisnac = e0476Paisnac;
		this.e0476FecCt = e0476FecCt;
		this.e0476SexoPer = e0476SexoPer;
		this.e0476TipoEst = e0476TipoEst;
		this.e0476Fechnaci = e0476Fechnaci;
		this.e0476IndNiva = e0476IndNiva;
		this.e0476Indemple = e0476Indemple;
		this.e0476Paisresi = e0476Paisresi;
		this.e0476Csecbes = e0476Csecbes;
		this.e0476Cnae93 = e0476Cnae93;
		this.e0476Nivestud = e0476Nivestud;
		this.e0476Codidio = e0476Codidio;
		this.e0476Idemprpp = e0476Idemprpp;
		this.e0476Incli = e0476Incli;
		this.e0476Cpais2na = e0476Cpais2na;
		this.e0476FecDece = e0476FecDece;
		this.e0476Swtrabj = e0476Swtrabj;
		this.e0476Cno = e0476Cno;
		this.e0476Fecaltsi = e0476Fecaltsi;
		this.e0476Usultact = e0476Usultact;
		this.e0476Emultact = e0476Emultact;
		this.e0476Ceultact = e0476Ceultact;
		this.e0476Feultact = e0476Feultact;
		this.e0476HorUlta = e0476HorUlta;
		this.e0476Indicado = e0476Indicado;
		this.e0476Codpais = e0476Codpais;
		this.e0476Paisresf = e0476Paisresf;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "e0476TipoPer", column = @Column(name = "e0476_tipo_per", nullable = false, length = 1)),
			@AttributeOverride(name = "e0476CodPers", column = @Column(name = "e0476_cod_pers", nullable = false)) })
	public PersFisicaUkId getId() {
		return this.id;
	}

	public void setId(PersFisicaUkId id) {
		this.id = id;
	}

	@Column(name = "e0476_cod_abr", length = 10)
	public String getE0476CodAbr() {
		return this.e0476CodAbr;
	}

	public void setE0476CodAbr(String e0476CodAbr) {
		this.e0476CodAbr = e0476CodAbr;
	}

	@Column(name = "e0476_tip_tra", length = 2)
	public String getE0476TipTra() {
		return this.e0476TipTra;
	}

	public void setE0476TipTra(String e0476TipTra) {
		this.e0476TipTra = e0476TipTra;
	}

	@Column(name = "e0476_first_nm", length = 50)
	public String getE0476FirstNm() {
		return this.e0476FirstNm;
	}

	public void setE0476FirstNm(String e0476FirstNm) {
		this.e0476FirstNm = e0476FirstNm;
	}

	@Column(name = "e0476_middl_nm", length = 100)
	public String getE0476MiddlNm() {
		return this.e0476MiddlNm;
	}

	public void setE0476MiddlNm(String e0476MiddlNm) {
		this.e0476MiddlNm = e0476MiddlNm;
	}

	@Column(name = "e0476_last_nm", nullable = false, length = 500)
	public String getE0476LastNm() {
		return this.e0476LastNm;
	}

	public void setE0476LastNm(String e0476LastNm) {
		this.e0476LastNm = e0476LastNm;
	}

	@Column(name = "e0476_tip_sufx", length = 2)
	public String getE0476TipSufx() {
		return this.e0476TipSufx;
	}

	public void setE0476TipSufx(String e0476TipSufx) {
		this.e0476TipSufx = e0476TipSufx;
	}

	@Column(name = "e0476_known_as", length = 30)
	public String getE0476KnownAs() {
		return this.e0476KnownAs;
	}

	public void setE0476KnownAs(String e0476KnownAs) {
		this.e0476KnownAs = e0476KnownAs;
	}

	@Column(name = "e0476_maidn_nm", length = 50)
	public String getE0476MaidnNm() {
		return this.e0476MaidnNm;
	}

	public void setE0476MaidnNm(String e0476MaidnNm) {
		this.e0476MaidnNm = e0476MaidnNm;
	}

	@Column(name = "e0476_infsrctp", length = 2)
	public String getE0476Infsrctp() {
		return this.e0476Infsrctp;
	}

	public void setE0476Infsrctp(String e0476Infsrctp) {
		this.e0476Infsrctp = e0476Infsrctp;
	}

	@Column(name = "e0476_paisnac", length = 2)
	public String getE0476Paisnac() {
		return this.e0476Paisnac;
	}

	public void setE0476Paisnac(String e0476Paisnac) {
		this.e0476Paisnac = e0476Paisnac;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0476_fec_ct", length = 13)
	public Date getE0476FecCt() {
		return this.e0476FecCt;
	}

	public void setE0476FecCt(Date e0476FecCt) {
		this.e0476FecCt = e0476FecCt;
	}

	@Column(name = "e0476_sexo_per", length = 1)
	public Character getE0476SexoPer() {
		return this.e0476SexoPer;
	}

	public void setE0476SexoPer(Character e0476SexoPer) {
		this.e0476SexoPer = e0476SexoPer;
	}

	@Column(name = "e0476_tipo_est", length = 1)
	public Character getE0476TipoEst() {
		return this.e0476TipoEst;
	}

	public void setE0476TipoEst(Character e0476TipoEst) {
		this.e0476TipoEst = e0476TipoEst;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0476_fechnaci", length = 13)
	public Date getE0476Fechnaci() {
		return this.e0476Fechnaci;
	}

	public void setE0476Fechnaci(Date e0476Fechnaci) {
		this.e0476Fechnaci = e0476Fechnaci;
	}

	@Column(name = "e0476_ind_niva", length = 2)
	public String getE0476IndNiva() {
		return this.e0476IndNiva;
	}

	public void setE0476IndNiva(String e0476IndNiva) {
		this.e0476IndNiva = e0476IndNiva;
	}

	@Column(name = "e0476_indemple", length = 1)
	public Character getE0476Indemple() {
		return this.e0476Indemple;
	}

	public void setE0476Indemple(Character e0476Indemple) {
		this.e0476Indemple = e0476Indemple;
	}

	@Column(name = "e0476_paisresi", length = 2)
	public String getE0476Paisresi() {
		return this.e0476Paisresi;
	}

	public void setE0476Paisresi(String e0476Paisresi) {
		this.e0476Paisresi = e0476Paisresi;
	}

	@Column(name = "e0476_csecbes", length = 3)
	public String getE0476Csecbes() {
		return this.e0476Csecbes;
	}

	public void setE0476Csecbes(String e0476Csecbes) {
		this.e0476Csecbes = e0476Csecbes;
	}

	@Column(name = "e0476_cnae93", length = 5)
	public String getE0476Cnae93() {
		return this.e0476Cnae93;
	}

	public void setE0476Cnae93(String e0476Cnae93) {
		this.e0476Cnae93 = e0476Cnae93;
	}

	@Column(name = "e0476_nivestud", length = 2)
	public String getE0476Nivestud() {
		return this.e0476Nivestud;
	}

	public void setE0476Nivestud(String e0476Nivestud) {
		this.e0476Nivestud = e0476Nivestud;
	}

	@Column(name = "e0476_codidio", length = 1)
	public Character getE0476Codidio() {
		return this.e0476Codidio;
	}

	public void setE0476Codidio(Character e0476Codidio) {
		this.e0476Codidio = e0476Codidio;
	}

	@Column(name = "e0476_idemprpp", length = 4)
	public String getE0476Idemprpp() {
		return this.e0476Idemprpp;
	}

	public void setE0476Idemprpp(String e0476Idemprpp) {
		this.e0476Idemprpp = e0476Idemprpp;
	}

	@Column(name = "e0476_incli", length = 2)
	public String getE0476Incli() {
		return this.e0476Incli;
	}

	public void setE0476Incli(String e0476Incli) {
		this.e0476Incli = e0476Incli;
	}

	@Column(name = "e0476_cpais2na", length = 2)
	public String getE0476Cpais2na() {
		return this.e0476Cpais2na;
	}

	public void setE0476Cpais2na(String e0476Cpais2na) {
		this.e0476Cpais2na = e0476Cpais2na;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0476_fec_dece", length = 13)
	public Date getE0476FecDece() {
		return this.e0476FecDece;
	}

	public void setE0476FecDece(Date e0476FecDece) {
		this.e0476FecDece = e0476FecDece;
	}

	@Column(name = "e0476_swtrabj", length = 1)
	public Character getE0476Swtrabj() {
		return this.e0476Swtrabj;
	}

	public void setE0476Swtrabj(Character e0476Swtrabj) {
		this.e0476Swtrabj = e0476Swtrabj;
	}

	@Column(name = "e0476_cno", length = 4)
	public String getE0476Cno() {
		return this.e0476Cno;
	}

	public void setE0476Cno(String e0476Cno) {
		this.e0476Cno = e0476Cno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0476_fecaltsi", length = 13)
	public Date getE0476Fecaltsi() {
		return this.e0476Fecaltsi;
	}

	public void setE0476Fecaltsi(Date e0476Fecaltsi) {
		this.e0476Fecaltsi = e0476Fecaltsi;
	}

	@Column(name = "e0476_usultact", length = 200)
	public String getE0476Usultact() {
		return this.e0476Usultact;
	}

	public void setE0476Usultact(String e0476Usultact) {
		this.e0476Usultact = e0476Usultact;
	}

	@Column(name = "e0476_emultact", length = 200)
	public String getE0476Emultact() {
		return this.e0476Emultact;
	}

	public void setE0476Emultact(String e0476Emultact) {
		this.e0476Emultact = e0476Emultact;
	}

	@Column(name = "e0476_ceultact", length = 200)
	public String getE0476Ceultact() {
		return this.e0476Ceultact;
	}

	public void setE0476Ceultact(String e0476Ceultact) {
		this.e0476Ceultact = e0476Ceultact;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0476_feultact", length = 13)
	public Date getE0476Feultact() {
		return this.e0476Feultact;
	}

	public void setE0476Feultact(Date e0476Feultact) {
		this.e0476Feultact = e0476Feultact;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "e0476_hor_ulta", length = 29)
	public Date getE0476HorUlta() {
		return this.e0476HorUlta;
	}

	public void setE0476HorUlta(Date e0476HorUlta) {
		this.e0476HorUlta = e0476HorUlta;
	}

	@Column(name = "e0476_indicado", length = 100)
	public String getE0476Indicado() {
		return this.e0476Indicado;
	}

	public void setE0476Indicado(String e0476Indicado) {
		this.e0476Indicado = e0476Indicado;
	}

	@Column(name = "e0476_codpais", length = 100)
	public String getE0476Codpais() {
		return this.e0476Codpais;
	}

	public void setE0476Codpais(String e0476Codpais) {
		this.e0476Codpais = e0476Codpais;
	}

	@Column(name = "e0476_paisresf", length = 100)
	public String getE0476Paisresf() {
		return this.e0476Paisresf;
	}

	public void setE0476Paisresf(String e0476Paisresf) {
		this.e0476Paisresf = e0476Paisresf;
	}

}
