package com.itc.dbservice.models;
// Generated 5 Jan, 2019 8:40:26 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersFisicaUkId generated by hbm2java
 */
@Embeddable
public class PersFisicaUkId implements java.io.Serializable {

	private char e0476TipoPer;
	private int e0476CodPers;

	public PersFisicaUkId() {
	}

	public PersFisicaUkId(char e0476TipoPer, int e0476CodPers) {
		this.e0476TipoPer = e0476TipoPer;
		this.e0476CodPers = e0476CodPers;
	}

	@Column(name = "e0476_tipo_per", nullable = false, length = 1)
	public char getE0476TipoPer() {
		return this.e0476TipoPer;
	}

	public void setE0476TipoPer(char e0476TipoPer) {
		this.e0476TipoPer = e0476TipoPer;
	}

	@Column(name = "e0476_cod_pers", nullable = false)
	public int getE0476CodPers() {
		return this.e0476CodPers;
	}

	public void setE0476CodPers(int e0476CodPers) {
		this.e0476CodPers = e0476CodPers;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersFisicaUkId))
			return false;
		PersFisicaUkId castOther = (PersFisicaUkId) other;

		return (this.getE0476TipoPer() == castOther.getE0476TipoPer())
				&& (this.getE0476CodPers() == castOther.getE0476CodPers());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getE0476TipoPer();
		result = 37 * result + this.getE0476CodPers();
		return result;
	}

}
