package com.itc.dbservice.models;
// Generated 5 Jan, 2019 8:40:26 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SccDirServ generated by hbm2java
 */
@Entity
@Table(name = "scc_dir_serv", schema = "alert_schema")
public class SccDirServ implements java.io.Serializable {

	private SccDirServId id;

	public SccDirServ() {
	}

	public SccDirServ(SccDirServId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "e0575Idemp", column = @Column(name = "e0575_idemp", nullable = false, length = 4)),
			@AttributeOverride(name = "e0575Idcent", column = @Column(name = "e0575_idcent", nullable = false, length = 4)),
			@AttributeOverride(name = "e0575Codprod", column = @Column(name = "e0575_codprod", nullable = false, length = 3)),
			@AttributeOverride(name = "e0575Idcontr", column = @Column(name = "e0575_idcontr", nullable = false, length = 7)),
			@AttributeOverride(name = "e0575Cdcanal", column = @Column(name = "e0575_cdcanal", nullable = false, length = 3)),
			@AttributeOverride(name = "e0575Tipopers", column = @Column(name = "e0575_tipopers", nullable = false, length = 1)),
			@AttributeOverride(name = "e0575Codpers", column = @Column(name = "e0575_codpers", precision = 9, scale = 0)),
			@AttributeOverride(name = "e0575Iddispo", column = @Column(name = "e0575_iddispo", nullable = false, length = 1)),
			@AttributeOverride(name = "e0575Jnrosec", column = @Column(name = "e0575_jnrosec", precision = 3, scale = 0)),
			@AttributeOverride(name = "e0575Defecto", column = @Column(name = "e0575_defecto", nullable = false, length = 10)),
			@AttributeOverride(name = "e0575Usumod", column = @Column(name = "e0575_usumod", nullable = false, length = 8)),
			@AttributeOverride(name = "e0575Fechaba1", column = @Column(name = "e0575_fechaba1", length = 100)),
			@AttributeOverride(name = "e0575Fechaal1", column = @Column(name = "e0575_fechaal1", length = 13)) })
	public SccDirServId getId() {
		return this.id;
	}

	public void setId(SccDirServId id) {
		this.id = id;
	}

}
