package com.itc.dbservice.models;
// Generated 5 Jan, 2019 8:40:26 PM by Hibernate Tools 5.0.6.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SccDirSuscr generated by hbm2java
 */
@Entity
@Table(name = "scc_dir_suscr", schema = "alert_schema")
public class SccDirSuscr implements Serializable {

	private Serializable uuid;
	private String e0565Idemp;
	private String e0565Codsus;
	private String e0565Cdcanal;
	private String e0565Codformx;
	private char e0565Codidio;
	private char e0565Tipopers;
	private Integer e0565Codpers;
	private String e0565Iddispo;
	private Short e0565Jnrosec;
	private char e0565Defecto;

	public SccDirSuscr() {
	}

	public SccDirSuscr(Serializable uuid, String e0565Idemp, String e0565Codsus, String e0565Cdcanal,
			String e0565Codformx, char e0565Codidio, char e0565Tipopers, String e0565Iddispo, char e0565Defecto) {
		this.uuid = uuid;
		this.e0565Idemp = e0565Idemp;
		this.e0565Codsus = e0565Codsus;
		this.e0565Cdcanal = e0565Cdcanal;
		this.e0565Codformx = e0565Codformx;
		this.e0565Codidio = e0565Codidio;
		this.e0565Tipopers = e0565Tipopers;
		this.e0565Iddispo = e0565Iddispo;
		this.e0565Defecto = e0565Defecto;
	}

	public SccDirSuscr(Serializable uuid, String e0565Idemp, String e0565Codsus, String e0565Cdcanal,
			String e0565Codformx, char e0565Codidio, char e0565Tipopers, Integer e0565Codpers, String e0565Iddispo,
			Short e0565Jnrosec, char e0565Defecto) {
		this.uuid = uuid;
		this.e0565Idemp = e0565Idemp;
		this.e0565Codsus = e0565Codsus;
		this.e0565Cdcanal = e0565Cdcanal;
		this.e0565Codformx = e0565Codformx;
		this.e0565Codidio = e0565Codidio;
		this.e0565Tipopers = e0565Tipopers;
		this.e0565Codpers = e0565Codpers;
		this.e0565Iddispo = e0565Iddispo;
		this.e0565Jnrosec = e0565Jnrosec;
		this.e0565Defecto = e0565Defecto;
	}

	@Id

	@Column(name = "uuid_", unique = true, nullable = false)
	public Serializable getUuid() {
		return this.uuid;
	}

	public void setUuid(Serializable uuid) {
		this.uuid = uuid;
	}

	@Column(name = "e0565_idemp", nullable = false, length = 4)
	public String getE0565Idemp() {
		return this.e0565Idemp;
	}

	public void setE0565Idemp(String e0565Idemp) {
		this.e0565Idemp = e0565Idemp;
	}

	@Column(name = "e0565_codsus", nullable = false, length = 15)
	public String getE0565Codsus() {
		return this.e0565Codsus;
	}

	public void setE0565Codsus(String e0565Codsus) {
		this.e0565Codsus = e0565Codsus;
	}

	@Column(name = "e0565_cdcanal", nullable = false, length = 3)
	public String getE0565Cdcanal() {
		return this.e0565Cdcanal;
	}

	public void setE0565Cdcanal(String e0565Cdcanal) {
		this.e0565Cdcanal = e0565Cdcanal;
	}

	@Column(name = "e0565_codformx", nullable = false, length = 2)
	public String getE0565Codformx() {
		return this.e0565Codformx;
	}

	public void setE0565Codformx(String e0565Codformx) {
		this.e0565Codformx = e0565Codformx;
	}

	@Column(name = "e0565_codidio", nullable = false, length = 1)
	public char getE0565Codidio() {
		return this.e0565Codidio;
	}

	public void setE0565Codidio(char e0565Codidio) {
		this.e0565Codidio = e0565Codidio;
	}

	@Column(name = "e0565_tipopers", nullable = false, length = 1)
	public char getE0565Tipopers() {
		return this.e0565Tipopers;
	}

	public void setE0565Tipopers(char e0565Tipopers) {
		this.e0565Tipopers = e0565Tipopers;
	}

	@Column(name = "e0565_codpers", precision = 9, scale = 0)
	public Integer getE0565Codpers() {
		return this.e0565Codpers;
	}

	public void setE0565Codpers(Integer e0565Codpers) {
		this.e0565Codpers = e0565Codpers;
	}

	@Column(name = "e0565_iddispo", nullable = false, length = 2)
	public String getE0565Iddispo() {
		return this.e0565Iddispo;
	}

	public void setE0565Iddispo(String e0565Iddispo) {
		this.e0565Iddispo = e0565Iddispo;
	}

	@Column(name = "e0565_jnrosec", precision = 3, scale = 0)
	public Short getE0565Jnrosec() {
		return this.e0565Jnrosec;
	}

	public void setE0565Jnrosec(Short e0565Jnrosec) {
		this.e0565Jnrosec = e0565Jnrosec;
	}

	@Column(name = "e0565_defecto", nullable = false, length = 1)
	public char getE0565Defecto() {
		return this.e0565Defecto;
	}

	public void setE0565Defecto(char e0565Defecto) {
		this.e0565Defecto = e0565Defecto;
	}

}
