package com.itc.dbservice.models;
// Generated 5 Jan, 2019 8:40:26 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SccSuscripcionId generated by hbm2java
 */
@Embeddable
public class SccSuscripcionId implements java.io.Serializable {

	private String e0338Idempr;
	private String e0338Codsus;

	public SccSuscripcionId() {
	}

	public SccSuscripcionId(String e0338Idempr, String e0338Codsus) {
		this.e0338Idempr = e0338Idempr;
		this.e0338Codsus = e0338Codsus;
	}

	@Column(name = "e0338_idempr", nullable = false, length = 4)
	public String getE0338Idempr() {
		return this.e0338Idempr;
	}

	public void setE0338Idempr(String e0338Idempr) {
		this.e0338Idempr = e0338Idempr;
	}

	@Column(name = "e0338_codsus", nullable = false, length = 15)
	public String getE0338Codsus() {
		return this.e0338Codsus;
	}

	public void setE0338Codsus(String e0338Codsus) {
		this.e0338Codsus = e0338Codsus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SccSuscripcionId))
			return false;
		SccSuscripcionId castOther = (SccSuscripcionId) other;

		return ((this.getE0338Idempr() == castOther.getE0338Idempr()) || (this.getE0338Idempr() != null
				&& castOther.getE0338Idempr() != null && this.getE0338Idempr().equals(castOther.getE0338Idempr())))
				&& ((this.getE0338Codsus() == castOther.getE0338Codsus())
						|| (this.getE0338Codsus() != null && castOther.getE0338Codsus() != null
								&& this.getE0338Codsus().equals(castOther.getE0338Codsus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getE0338Idempr() == null ? 0 : this.getE0338Idempr().hashCode());
		result = 37 * result + (getE0338Codsus() == null ? 0 : this.getE0338Codsus().hashCode());
		return result;
	}

}
