package com.itc.dbservice.models;
// Generated 5 Jan, 2019 8:40:26 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SccSuscripcion generated by hbm2java
 */
@Entity
@Table(name = "scc_suscripcion", schema = "alert_schema")
public class SccSuscripcion implements java.io.Serializable {

	private SccSuscripcionId id;
	private String e0338Agrucent;
	private char e0338Tipopers;
	private Integer e0338Codpers;
	private String e0338Tipcomu1;
	private String e0338Coperiod;
	private Date e0338Fechaal1;
	private Date e0338Fecomval;
	private Date e0338Fefinval;
	private Date e0338Fechaba1;
	private Date e0338Feculten;
	private Integer e0338Grufunc;
	private String e0338Cdcanal;
	private Date e0338FecModi;
	private String e0338Uid;
	private String e0338Centrusu;

	public SccSuscripcion() {
	}

	public SccSuscripcion(SccSuscripcionId id, String e0338Agrucent, char e0338Tipopers, String e0338Tipcomu1,
			String e0338Uid, String e0338Centrusu) {
		this.id = id;
		this.e0338Agrucent = e0338Agrucent;
		this.e0338Tipopers = e0338Tipopers;
		this.e0338Tipcomu1 = e0338Tipcomu1;
		this.e0338Uid = e0338Uid;
		this.e0338Centrusu = e0338Centrusu;
	}

	public SccSuscripcion(SccSuscripcionId id, String e0338Agrucent, char e0338Tipopers, Integer e0338Codpers,
			String e0338Tipcomu1, String e0338Coperiod, Date e0338Fechaal1, Date e0338Fecomval, Date e0338Fefinval,
			Date e0338Fechaba1, Date e0338Feculten, Integer e0338Grufunc, String e0338Cdcanal, Date e0338FecModi,
			String e0338Uid, String e0338Centrusu) {
		this.id = id;
		this.e0338Agrucent = e0338Agrucent;
		this.e0338Tipopers = e0338Tipopers;
		this.e0338Codpers = e0338Codpers;
		this.e0338Tipcomu1 = e0338Tipcomu1;
		this.e0338Coperiod = e0338Coperiod;
		this.e0338Fechaal1 = e0338Fechaal1;
		this.e0338Fecomval = e0338Fecomval;
		this.e0338Fefinval = e0338Fefinval;
		this.e0338Fechaba1 = e0338Fechaba1;
		this.e0338Feculten = e0338Feculten;
		this.e0338Grufunc = e0338Grufunc;
		this.e0338Cdcanal = e0338Cdcanal;
		this.e0338FecModi = e0338FecModi;
		this.e0338Uid = e0338Uid;
		this.e0338Centrusu = e0338Centrusu;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "e0338Idempr", column = @Column(name = "e0338_idempr", nullable = false, length = 4)),
			@AttributeOverride(name = "e0338Codsus", column = @Column(name = "e0338_codsus", nullable = false, length = 15)) })
	public SccSuscripcionId getId() {
		return this.id;
	}

	public void setId(SccSuscripcionId id) {
		this.id = id;
	}

	@Column(name = "e0338_agrucent", nullable = false, length = 4)
	public String getE0338Agrucent() {
		return this.e0338Agrucent;
	}

	public void setE0338Agrucent(String e0338Agrucent) {
		this.e0338Agrucent = e0338Agrucent;
	}

	@Column(name = "e0338_tipopers", nullable = false, length = 1)
	public char getE0338Tipopers() {
		return this.e0338Tipopers;
	}

	public void setE0338Tipopers(char e0338Tipopers) {
		this.e0338Tipopers = e0338Tipopers;
	}

	@Column(name = "e0338_codpers", precision = 9, scale = 0)
	public Integer getE0338Codpers() {
		return this.e0338Codpers;
	}

	public void setE0338Codpers(Integer e0338Codpers) {
		this.e0338Codpers = e0338Codpers;
	}

	@Column(name = "e0338_tipcomu1", nullable = false, length = 9)
	public String getE0338Tipcomu1() {
		return this.e0338Tipcomu1;
	}

	public void setE0338Tipcomu1(String e0338Tipcomu1) {
		this.e0338Tipcomu1 = e0338Tipcomu1;
	}

	@Column(name = "e0338_coperiod", length = 3)
	public String getE0338Coperiod() {
		return this.e0338Coperiod;
	}

	public void setE0338Coperiod(String e0338Coperiod) {
		this.e0338Coperiod = e0338Coperiod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0338_fechaal1", length = 13)
	public Date getE0338Fechaal1() {
		return this.e0338Fechaal1;
	}

	public void setE0338Fechaal1(Date e0338Fechaal1) {
		this.e0338Fechaal1 = e0338Fechaal1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0338_fecomval", length = 13)
	public Date getE0338Fecomval() {
		return this.e0338Fecomval;
	}

	public void setE0338Fecomval(Date e0338Fecomval) {
		this.e0338Fecomval = e0338Fecomval;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0338_fefinval", length = 13)
	public Date getE0338Fefinval() {
		return this.e0338Fefinval;
	}

	public void setE0338Fefinval(Date e0338Fefinval) {
		this.e0338Fefinval = e0338Fefinval;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0338_fechaba1", length = 13)
	public Date getE0338Fechaba1() {
		return this.e0338Fechaba1;
	}

	public void setE0338Fechaba1(Date e0338Fechaba1) {
		this.e0338Fechaba1 = e0338Fechaba1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0338_feculten", length = 13)
	public Date getE0338Feculten() {
		return this.e0338Feculten;
	}

	public void setE0338Feculten(Date e0338Feculten) {
		this.e0338Feculten = e0338Feculten;
	}

	@Column(name = "e0338_grufunc")
	public Integer getE0338Grufunc() {
		return this.e0338Grufunc;
	}

	public void setE0338Grufunc(Integer e0338Grufunc) {
		this.e0338Grufunc = e0338Grufunc;
	}

	@Column(name = "e0338_cdcanal", length = 3)
	public String getE0338Cdcanal() {
		return this.e0338Cdcanal;
	}

	public void setE0338Cdcanal(String e0338Cdcanal) {
		this.e0338Cdcanal = e0338Cdcanal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "e0338_fec_modi", length = 29)
	public Date getE0338FecModi() {
		return this.e0338FecModi;
	}

	public void setE0338FecModi(Date e0338FecModi) {
		this.e0338FecModi = e0338FecModi;
	}

	@Column(name = "e0338_uid", nullable = false, length = 30)
	public String getE0338Uid() {
		return this.e0338Uid;
	}

	public void setE0338Uid(String e0338Uid) {
		this.e0338Uid = e0338Uid;
	}

	@Column(name = "e0338_centrusu", nullable = false, length = 4)
	public String getE0338Centrusu() {
		return this.e0338Centrusu;
	}

	public void setE0338Centrusu(String e0338Centrusu) {
		this.e0338Centrusu = e0338Centrusu;
	}

}
