package com.itc.dbservice.models;
// Generated 5 Jan, 2019 8:40:26 PM by Hibernate Tools 5.0.6.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SccSuscrCont generated by hbm2java
 */
@Entity
@Table(name = "scc_suscr_cont", schema = "alert_schema")
public class SccSuscrCont implements Serializable {

	private Serializable uuid;
	private String e0353Idempr;
	private String e0353Codsus;
	private String e0353Idempre;
	private String e0353Idcent;
	private String e0353Idprod;
	private String e0353Idcontr;
	private Date e0353Fechaal1;
	private Date e0353Fechaba1;
	private String e0353Usumod;
	private String e0353Codmonsw;

	public SccSuscrCont() {
	}

	public SccSuscrCont(Serializable uuid, String e0353Idempr, String e0353Codsus, String e0353Idempre,
			String e0353Idcent, String e0353Idprod, String e0353Idcontr) {
		this.uuid = uuid;
		this.e0353Idempr = e0353Idempr;
		this.e0353Codsus = e0353Codsus;
		this.e0353Idempre = e0353Idempre;
		this.e0353Idcent = e0353Idcent;
		this.e0353Idprod = e0353Idprod;
		this.e0353Idcontr = e0353Idcontr;
	}

	public SccSuscrCont(Serializable uuid, String e0353Idempr, String e0353Codsus, String e0353Idempre,
			String e0353Idcent, String e0353Idprod, String e0353Idcontr, Date e0353Fechaal1, Date e0353Fechaba1,
			String e0353Usumod, String e0353Codmonsw) {
		this.uuid = uuid;
		this.e0353Idempr = e0353Idempr;
		this.e0353Codsus = e0353Codsus;
		this.e0353Idempre = e0353Idempre;
		this.e0353Idcent = e0353Idcent;
		this.e0353Idprod = e0353Idprod;
		this.e0353Idcontr = e0353Idcontr;
		this.e0353Fechaal1 = e0353Fechaal1;
		this.e0353Fechaba1 = e0353Fechaba1;
		this.e0353Usumod = e0353Usumod;
		this.e0353Codmonsw = e0353Codmonsw;
	}

	@Id

	@Column(name = "uuid_", unique = true, nullable = false)
	public Serializable getUuid() {
		return this.uuid;
	}

	public void setUuid(Serializable uuid) {
		this.uuid = uuid;
	}

	@Column(name = "e0353_idempr", nullable = false, length = 4)
	public String getE0353Idempr() {
		return this.e0353Idempr;
	}

	public void setE0353Idempr(String e0353Idempr) {
		this.e0353Idempr = e0353Idempr;
	}

	@Column(name = "e0353_codsus", nullable = false, length = 15)
	public String getE0353Codsus() {
		return this.e0353Codsus;
	}

	public void setE0353Codsus(String e0353Codsus) {
		this.e0353Codsus = e0353Codsus;
	}

	@Column(name = "e0353_idempre", nullable = false, length = 4)
	public String getE0353Idempre() {
		return this.e0353Idempre;
	}

	public void setE0353Idempre(String e0353Idempre) {
		this.e0353Idempre = e0353Idempre;
	}

	@Column(name = "e0353_idcent", nullable = false, length = 4)
	public String getE0353Idcent() {
		return this.e0353Idcent;
	}

	public void setE0353Idcent(String e0353Idcent) {
		this.e0353Idcent = e0353Idcent;
	}

	@Column(name = "e0353_idprod", nullable = false, length = 3)
	public String getE0353Idprod() {
		return this.e0353Idprod;
	}

	public void setE0353Idprod(String e0353Idprod) {
		this.e0353Idprod = e0353Idprod;
	}

	@Column(name = "e0353_idcontr", nullable = false, length = 7)
	public String getE0353Idcontr() {
		return this.e0353Idcontr;
	}

	public void setE0353Idcontr(String e0353Idcontr) {
		this.e0353Idcontr = e0353Idcontr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0353_fechaal1", length = 13)
	public Date getE0353Fechaal1() {
		return this.e0353Fechaal1;
	}

	public void setE0353Fechaal1(Date e0353Fechaal1) {
		this.e0353Fechaal1 = e0353Fechaal1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0353_fechaba1", length = 13)
	public Date getE0353Fechaba1() {
		return this.e0353Fechaba1;
	}

	public void setE0353Fechaba1(Date e0353Fechaba1) {
		this.e0353Fechaba1 = e0353Fechaba1;
	}

	@Column(name = "e0353_usumod", length = 8)
	public String getE0353Usumod() {
		return this.e0353Usumod;
	}

	public void setE0353Usumod(String e0353Usumod) {
		this.e0353Usumod = e0353Usumod;
	}

	@Column(name = "e0353_codmonsw", length = 3)
	public String getE0353Codmonsw() {
		return this.e0353Codmonsw;
	}

	public void setE0353Codmonsw(String e0353Codmonsw) {
		this.e0353Codmonsw = e0353Codmonsw;
	}

}
