package com.itc.dbservice.models;
// Generated 5 Jan, 2019 8:40:26 PM by Hibernate Tools 5.0.6.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SccServicio generated by hbm2java
 */
@Entity
@Table(name = "scc_servicio", schema = "alert_schema")
public class SccServicio implements Serializable {

	private Serializable uuid;
	private String e0340Idempr;
	private String e0340Idcent;
	private String e0340Codprod;
	private String e0340Idcontr;
	private String e0340Idsubpro;
	private Character e0340Tipopers;
	private Integer e0340Codpers;
	private String e0340Codmonsw;
	private String e0340Codtarap;
	private String e0340Coestref;
	private Character e0340Idtipsco;
	private Date e0340Fechaal1;
	private Date e0340Fechaba1;
	private String e0340Cdcanal;
	private String e0340Uid;
	private String e0340Motivcam;
	private String e0340Memoword;
	private String e0340Centrusu;

	public SccServicio() {
	}

	public SccServicio(Serializable uuid, String e0340Idempr, String e0340Idcent, String e0340Codprod,
			String e0340Idcontr) {
		this.uuid = uuid;
		this.e0340Idempr = e0340Idempr;
		this.e0340Idcent = e0340Idcent;
		this.e0340Codprod = e0340Codprod;
		this.e0340Idcontr = e0340Idcontr;
	}

	public SccServicio(Serializable uuid, String e0340Idempr, String e0340Idcent, String e0340Codprod,
			String e0340Idcontr, String e0340Idsubpro, Character e0340Tipopers, Integer e0340Codpers,
			String e0340Codmonsw, String e0340Codtarap, String e0340Coestref, Character e0340Idtipsco,
			Date e0340Fechaal1, Date e0340Fechaba1, String e0340Cdcanal, String e0340Uid, String e0340Motivcam,
			String e0340Memoword, String e0340Centrusu) {
		this.uuid = uuid;
		this.e0340Idempr = e0340Idempr;
		this.e0340Idcent = e0340Idcent;
		this.e0340Codprod = e0340Codprod;
		this.e0340Idcontr = e0340Idcontr;
		this.e0340Idsubpro = e0340Idsubpro;
		this.e0340Tipopers = e0340Tipopers;
		this.e0340Codpers = e0340Codpers;
		this.e0340Codmonsw = e0340Codmonsw;
		this.e0340Codtarap = e0340Codtarap;
		this.e0340Coestref = e0340Coestref;
		this.e0340Idtipsco = e0340Idtipsco;
		this.e0340Fechaal1 = e0340Fechaal1;
		this.e0340Fechaba1 = e0340Fechaba1;
		this.e0340Cdcanal = e0340Cdcanal;
		this.e0340Uid = e0340Uid;
		this.e0340Motivcam = e0340Motivcam;
		this.e0340Memoword = e0340Memoword;
		this.e0340Centrusu = e0340Centrusu;
	}

	@Id

	@Column(name = "uuid_", unique = true, nullable = false)
	public Serializable getUuid() {
		return this.uuid;
	}

	public void setUuid(Serializable uuid) {
		this.uuid = uuid;
	}

	@Column(name = "e0340_idempr", nullable = false, length = 4)
	public String getE0340Idempr() {
		return this.e0340Idempr;
	}

	public void setE0340Idempr(String e0340Idempr) {
		this.e0340Idempr = e0340Idempr;
	}

	@Column(name = "e0340_idcent", nullable = false, length = 4)
	public String getE0340Idcent() {
		return this.e0340Idcent;
	}

	public void setE0340Idcent(String e0340Idcent) {
		this.e0340Idcent = e0340Idcent;
	}

	@Column(name = "e0340_codprod", nullable = false, length = 3)
	public String getE0340Codprod() {
		return this.e0340Codprod;
	}

	public void setE0340Codprod(String e0340Codprod) {
		this.e0340Codprod = e0340Codprod;
	}

	@Column(name = "e0340_idcontr", nullable = false, length = 7)
	public String getE0340Idcontr() {
		return this.e0340Idcontr;
	}

	public void setE0340Idcontr(String e0340Idcontr) {
		this.e0340Idcontr = e0340Idcontr;
	}

	@Column(name = "e0340_idsubpro", length = 3)
	public String getE0340Idsubpro() {
		return this.e0340Idsubpro;
	}

	public void setE0340Idsubpro(String e0340Idsubpro) {
		this.e0340Idsubpro = e0340Idsubpro;
	}

	@Column(name = "e0340_tipopers", length = 1)
	public Character getE0340Tipopers() {
		return this.e0340Tipopers;
	}

	public void setE0340Tipopers(Character e0340Tipopers) {
		this.e0340Tipopers = e0340Tipopers;
	}

	@Column(name = "e0340_codpers", precision = 9, scale = 0)
	public Integer getE0340Codpers() {
		return this.e0340Codpers;
	}

	public void setE0340Codpers(Integer e0340Codpers) {
		this.e0340Codpers = e0340Codpers;
	}

	@Column(name = "e0340_codmonsw", length = 3)
	public String getE0340Codmonsw() {
		return this.e0340Codmonsw;
	}

	public void setE0340Codmonsw(String e0340Codmonsw) {
		this.e0340Codmonsw = e0340Codmonsw;
	}

	@Column(name = "e0340_codtarap", length = 3)
	public String getE0340Codtarap() {
		return this.e0340Codtarap;
	}

	public void setE0340Codtarap(String e0340Codtarap) {
		this.e0340Codtarap = e0340Codtarap;
	}

	@Column(name = "e0340_coestref", length = 7)
	public String getE0340Coestref() {
		return this.e0340Coestref;
	}

	public void setE0340Coestref(String e0340Coestref) {
		this.e0340Coestref = e0340Coestref;
	}

	@Column(name = "e0340_idtipsco", length = 1)
	public Character getE0340Idtipsco() {
		return this.e0340Idtipsco;
	}

	public void setE0340Idtipsco(Character e0340Idtipsco) {
		this.e0340Idtipsco = e0340Idtipsco;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0340_fechaal1", length = 13)
	public Date getE0340Fechaal1() {
		return this.e0340Fechaal1;
	}

	public void setE0340Fechaal1(Date e0340Fechaal1) {
		this.e0340Fechaal1 = e0340Fechaal1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e0340_fechaba1", length = 13)
	public Date getE0340Fechaba1() {
		return this.e0340Fechaba1;
	}

	public void setE0340Fechaba1(Date e0340Fechaba1) {
		this.e0340Fechaba1 = e0340Fechaba1;
	}

	@Column(name = "e0340_cdcanal", length = 3)
	public String getE0340Cdcanal() {
		return this.e0340Cdcanal;
	}

	public void setE0340Cdcanal(String e0340Cdcanal) {
		this.e0340Cdcanal = e0340Cdcanal;
	}

	@Column(name = "e0340_uid", length = 30)
	public String getE0340Uid() {
		return this.e0340Uid;
	}

	public void setE0340Uid(String e0340Uid) {
		this.e0340Uid = e0340Uid;
	}

	@Column(name = "e0340_motivcam", length = 200)
	public String getE0340Motivcam() {
		return this.e0340Motivcam;
	}

	public void setE0340Motivcam(String e0340Motivcam) {
		this.e0340Motivcam = e0340Motivcam;
	}

	@Column(name = "e0340_memoword", length = 10)
	public String getE0340Memoword() {
		return this.e0340Memoword;
	}

	public void setE0340Memoword(String e0340Memoword) {
		this.e0340Memoword = e0340Memoword;
	}

	@Column(name = "e0340_centrusu", length = 4)
	public String getE0340Centrusu() {
		return this.e0340Centrusu;
	}

	public void setE0340Centrusu(String e0340Centrusu) {
		this.e0340Centrusu = e0340Centrusu;
	}

}
